before_script:
  - pip install uv
  - uv sync --no-dev --frozen

stages:
 - check
 - unittest

check:
  stage: check
  script:
    - uv run poe lint
  tags:
    - {{ cookiecutter.project_name }}

unittest:
  stage: unittest
  script:
    - uv run poe test
  tags:
    - {{ cookiecutter.project_name }}
