before_script:
  - pip install pipenv
  - pipenv install --deploy --dev --skip-lock

stages:
 - check
 - unittest

check:
  stage: check
  script:
    - inv check
  tags:
    - {{ cookiecutter.project_name }}

unittest:
  stage: unittest
  script:
    - inv unittest
  tags:
    - {{ cookiecutter.project_name }}
