name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: {{ cookiecutter.python_version }}

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --skip-lock

      - run: inv check
      - run: inv unittest
      - run: inv coverage

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t {{ cookiecutter.project_name }}:test

      - name: Smoke test docker image
        run: |
          docker run --rm {{ cookiecutter.project_name }}:test
